---
title: '<div><b>Resources and Notes for Johns Hopkins Masters in Analytics and Policy</b> </div>'
output:
   html_document:
        toc: TRUE
        toc_depth: 3
        toc_float:
          collapsed: false
---

<style>
  table {
    border-collapse: collapse;
  }

  th, td {
    padding: 5px;
  }
</style>


<!--
*
* introduction
*
-->

<h1>Introduction</h1>
This site provides links to the resources I commonly used during my Masters of Analytics and Policy at Johns Hopkins.
<h1>Quick Links</h1>

<!--
*
* Links to Links
*
-->

<h2>Links to Links</h2>
This section has links to pages with multiple resources.
<br/><br/>
<table border="1" width="100%">
  <!-- research tools -->
  <tr>
    <td valign="top" width="20%">
      <a href="./research-tools.html"><nobr>Research&nbsp;Tools</nobr></a>&nbsp;&nbsp;
    </td>
    <td valign="top">
      A list of links for tools to do searches of the scietific literature, Johns Hopkins library, and other types of resources.  
    </td>
  </tr>
</table>

<!--
*
* General Links
*
-->

<h2>General Links</h2>
<table border="1" width="100%">

  <!-- data analytics and policy, master of science -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://e-catalogue.jhu.edu/arts-sciences/advanced-academic-programs/programs/center-advanced-governmental-studies/data-analytics-policy-master-science/#requirementstext">Data Analytics and Policy MS</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Data Analytics and Policy, Master of Science
    </td>
  </tr>

  <!-- academic calendar -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://advanced.jhu.edu/student-resources/academic-calendar/">Academic Calendar</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Academic Calendar: Registration start and end dates, semester start and end dates, etc.
    </td>
  </tr>

  <!-- class schedule -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://sis.jhu.edu/sswf/SSS/EntityClassSchedule/SSS_StudentClassScheduleOverView.aspx?CalledFrom=FromWeekCal">Class Schedule</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Schedule of classes. If you are only taking asyncronous classes this will be blank.  
    </td>
  </tr>

  <!-- canvas -->
  <tr>
    <td valign="top" width="20%">
      <a href="http://canvas.jhu.edu">Canvas</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Canvas: site used to manage your course work. 
    </td>
  </tr>

  <!-- sis log on -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://sis.jhu.edu/">SIS Log On</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Student Information Systems (SIS) Logon
    </td>
  </tr>

  <!-- grades -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://sis.jhu.edu/sswf/SSS/ViewGradesByAP/SSS_ViewGradesByAP.aspx?MyIndex=88311">Grades</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Grades (note, there is also a link to download unofficial transcript towards the top of this page)
    </td>
  </tr>

  <!-- unofficial transcript -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://sis.jhu.edu/sswf/SSS/ViewGradesByAP/SSS_ViewGradesByAP.aspx?MyIndex=88311">Unofficial Transcript</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Note, this is the link for grades. There is a link to download your unofficial transcript towards the top of this page. 
    </td>
  </tr>

  <!-- class search -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://sis.jhu.edu/sswf/SSS/SearchForClasses/SSS_SearchForClasses.aspx?MyIndex=125106">Class Search</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Class Search: Search for classes by name and semester
    </td>
  </tr>

  <!-- registration  -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://sis.jhu.edu/sswf/SSS/SSS_AddDropClasses/SSS_AddDropClasses.aspx?MyIndex=125108">Registration</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Registration: Register for classes
    </td>
  </tr>

  <!-- add drop -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://sis.jhu.edu/sswf/SSS/SSS_AddDropClasses/SSS_AddDropClasses.aspx?MyIndex=125108">Add/Drop</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Add/Drop: Add or Drop classes
    </td>
  </tr>

  <!-- billing -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://sis.jhu.edu/sswf/v/billing-summary/?MyIndex=88323">Billing</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Billing summary. Links to make payments, etc.
    </td>
  </tr>

  <!-- -->
  <tr>
    <td valign="top" width="20%">
      <a href=""></a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      
    </td>
  </tr>

  <!-- -->
  <tr>
    <td valign="top" width="20%">
      <a href=""></a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      
    </td>
  </tr>

  <!-- -->
  <tr>
    <td valign="top" width="20%">
      <a href=""></a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      
    </td>
  </tr>

  <!-- -->
  <tr>
    <td valign="top" width="20%">
      <a href=""></a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      
    </td>
  </tr>


</table>

<!--
*
* Career Management
*
-->

<h2>Career Management</h2>
<table border="1" width="100%">
  <!-- imagin homepage -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://imagine.jhu.edu/">Imagine Homepage</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      This page has a number of resources for career management including Hopkins Connect, Hopkins Office for Undergraduate Research (HOUR), Doctoral Life Design Studio (DLDS), and Hire Hopkins. The current zoom link is: <a href="https://zoom.us/j/3082142418">https://zoom.us/j/3082142418</a>
    </td>
  </tr>
  <!-- handshake channels homepage -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://imagine.jhu.edu/channels/explore-opportunities-ldl/">Handshake Channels Homepage</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      This page has a number of resources for career management including Handshake, One Hop Mentoring. The current zoom link is: <a href="https://zoom.us/j/3082142418">https://zoom.us/j/3082142418</a>
    </td>
  </tr>
  <!-- handshake homepage -->
  <tr>
    <td valign="top">
      <a href="https://jhu.joinhandshake.com/explore">Handshake Homepage</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      This page has a number of resources for career management including jobs, people, and a link to the career center. 
      <br/>
      The current zoom link is: <a href="https://zoom.us/j/3082142418">https://zoom.us/j/3082142418</a>
    </td>
  </tr>
  <!-- link to zoom meeting -->
  <tr>
    <td valign="top">
      <a href="https://imagine.jhu.edu/channels/life-design-lab/">Life Design Lab Drop in Hours</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      This page has the link to the Zoom meeting for life design lab drop-in hours (Monday - Thursday 1-5 p.m.)
      <br/>
      The current zoom link is: <a href="https://zoom.us/j/3082142418">https://zoom.us/j/3082142418</a>
    </td>
  </tr>
  <!-- job postings -->
  <tr>
    <td valign="top">
      <a href="https://jhu.joinhandshake.com/stu/postings">Job Postings</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Johns Hopkins job postings for external jobs
    </td>
  </tr>
  <!-- one hop -->
  <tr>
    <td valign="top">
      <a href="https://onehop.jhu.edu/hub/main/home-v3">One Hop Mentoring</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      A Hopkins networking site. Select the "Find the best career path for me" tab and then "Opt In" to sign up for alum mentors. 
    </td>
  </tr>
  <!-- sign up for mentor -->
  <tr>
    <td valign="top">
      <a href="https://imagine.jhu.edu/channels/getting-curious-for-the-jhu-community/">Sign Up for a Mentor</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Site with links including sign up for mentor
    </td>
  </tr>
  <!-- navigating transitions -->
  <tr>
    <td valign="top">
      <a href="https://imagine.jhu.edu/navigating-transitions/">Navigating Transitions</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Navigating Transitions: Register for seminars on career development
    </td>
  </tr>
  <!-- navigating transitions -->
  <tr>
    <td valign="top">
      <a href="https://imagine.jhu.edu/events/navigating-transitions/">Navigating Transitions (all events)</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Navigating Transitions Events: Register for seminars on career development (all events)
    </td>
  </tr>
  <!-- interesting links -->
  <tr>
    <td valign="top">
      <a href="https://imagine.jhu.edu/search/?type=&s=https%3A%2F%2Fzoom.us%2Fj%2F3082142418">Interesting Links</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Here's some interesting links that came up when I searched for the zoom meeting for the Life Design Lab zoom meeting. I don't know how fresh this page will be. 
      Most of these links are listed below.
    </td>
  </tr>
  <!-- job boards for public health professionals -->
  <tr>
    <td valign="top">
      <a href="https://imagine.jhu.edu/resources/comprehensive-job-boards-and-resources-for-public-health-professionals/">Job Board for Public Health Officials</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Comprehensive Job Boards and Resources for Public Health Professionals
    </td>
  </tr>
  <!-- breaking into global public health -->
  <tr>
    <td valign="top">
      <a href="https://imagine.jhu.edu/resources/189585/">Breaking into Public Health</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Breaking into Global Public Health: Key Takeaways from Careers at WHO & Gates Foundation
    </td>
  </tr>
  <!-- resume writing -->
  <tr>
    <td valign="top">
      <a href="https://imagine.jhu.edu/resources/how-to-write-effective-resumes-and-cvs-for-doctoral-students-and-postdocs/">Resume Writing</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      How to Write Effective Resumes and CVs for Doctoral Students and Postdocs
    </td>
  </tr>
  <!-- interview tips -->
  <tr>
    <td valign="top">
      <a href="https://imagine.jhu.edu/resources/interviewing-strategies-for-phds/">Interview Tips</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Interviewing Strategies for PhDs
    </td>
  </tr>
  <!-- museums and cultural institutions -->
  <tr>
    <td valign="top">
      <a href="https://imagine.jhu.edu/resources/museums-cultural-institutions-a-career-guide/">Museums and Cultural Institutions</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Museums & Cultural Institutions: A Career Guide 
    </td>
  </tr>
</table>


