---
title: '<div><b>Physical Fitness</b> </div>'
output:
   html_document:
        toc: TRUE
        toc_depth: 3
        toc_float:
          collapsed: false
---

<style>
  table {
    border-collapse: collapse;
  }

  th, td {
    padding: 5px;
  }
</style>


<!--
*
* introduction
*
-->

<h1>Introduction</h1>
We spend far too much time immobile, but such is the life of a scholar.
This page has mobility, flexibility, and cardiovascular exercises that will help to keep your body happy while you are growing your mind.

<!--
*
* Physical Fitness Links
*
-->

<h1>Physical Fitness</h1>

<!--
*
* Yoga
*
-->

<h2>Yoga</h2>
Low impact stretching exercises.
I started doing yoga about a two years ago.
I'm on the overweight side and have had lower back issues for most of my adult life.
Yoga has been the best thing to happen to my lower back by far.
100/10, would highly recommend.

<table border="1" width="100%">
  <!-- Cassandra's 20 Min Morning -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.youtube.com/watch?v=EuAwhogdukQ&t=4s">Cassandra's 20 Min Morning</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      A great 20 minute morning yoga routine.
      Excellent for beginners and can be modified as your abilities grow.
      This is where I started my yoga journey and I haven't looked back.
      Best thing to happen to me physical fitness wise since high school sports.
    </td>
  </tr>
</table>

<!--
*
* Mobility
*
-->

<h2>Mobility</h2>
Exercises that improve your mobility.

<table border="1" width="100%">
  <!-- Three Simple Beginner Mobility Moves -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/465079929661573">Three Simple Beginner Mobility Moves</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Three Simple Beginner Mobility Moves
      <ul>
        <li>Sit Throughs</li>
        <li>Plank Jacks</li>
        <li>Box Cross Reach</li>
      </ul>
    </td>
  </tr>
  <!-- build-up to kickout and reach up -->
  <tr>
    <td valign="top" width="20%">
      <a href="">Build-up to Kick-Out and Reach up</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Good for core and lower back.
    </td>
  </tr>
  <!-- Floor Exercise for Core -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1181237606255287">Floor Exercise for Core</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Floor Exercise for Core
    </td>
  </tr>
  <!-- Body Weight Workout -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1671255856992626">Body Weight Workout</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Body Weigh Workout
      <ul>
        <li>Side Jump to Front Kick</li>
        <li>One Hand Knee to Floor Dragon Squat</li>
        <li>Step Under to Low Squat</li>
        <li>Table Touch to Hollow Hold</li>
        <li>Side Kick to Back Lunge</li>
      </ul>
    </td>
  </tr>
  <!-- Exercises for Explosive Legs -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/917333280434765">Exercises for Explosive Legs</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Exercises for Explosive Legs
      <ul>
        <li>Sprawl to High Kick</li>
        <li>Side Kick Squat Jump</li>
        <li>Jump Over Mountain Climbers</li>
        <li>Skater to Front Kick</li>
      </ul>
    </td>
  </tr>
  <!-- Do this Instead of Cardio -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1481557962467872">Do this Instead of Cardio</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Do this Instead of Cardio
      <ul>
        <li>Table Switches Knee In</li>
        <li>Front Jump Crawl Variation Back</li>
        <li>Step Monkey Turn to Lunges Back</li>
        <li>M. Climbers/stair Pushups</li>
      </ul>
    </td>
  </tr>
  <!-- Beginner Mobility Moves -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/2238386619871119">Beginner Mobility Moves</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Beginner Mobility Moves, Try these after long periods of sitting down.
      <ul>
        <li>Foot Around Arm to Cross Downward Facing Dog</li>
        <li>Reach Backs to Table</li>
        <li>Kick Out Hamstring Flow</li>
        <li>Kneeling Spine Twist to Cobra Pushup</li>
      </ul>
    </td>
  </tr>
  <!-- Advanced Abs -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1019778429374745">Advanced Abs</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Advanced Abs Workout
    </td>
  </tr>
  <!-- Quick Movement Workout -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/371812975311719">Quick Movement Workout</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Quick Movement Workout (advanced yoga flow and cardio)
      <ul>
        <li>Hip Switch</li>
        <li>Kick Through</li>
        <li>Reverse Burpee (sprawl)</li>
      </ul>
    </td>
  </tr>
  <!-- Core, Knees, and Ankles -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/991483209442677">Core, Knees, and Ankles</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Simple and Short Flow for Core, Knees, and Ankles
    </td>
  </tr>
  <!-- Intermediate Core Flow -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1200688447748103">Intermediate Core Flow</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Intermediate Core Flow
      <ul>
        <li>Hook PUshups</li>
        <li>Compression Slides</li>
        <li>Row Reach to Plank</li>
        <li>Kick Out Lunges</li>
      </ul>
    </td>
  </tr>
  <!-- Step Out Variations -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/461676406844608">Step Out Variations</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Step Out Variations
      <ul>
        <li>Step out</li>
        <li>Touch Hand to Foot</li>
        <li>Step Knee In</li>
        <li>Knee to Arm</li>
        <li>Knee High to Low</li>
        <li>Hips High Step Back</li>
        <li>Foot Around Arm Touch</li>
      </ul>
    </td>
  </tr>
  <!-- A Mobility Sampler -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1246810966284946">A Mobility Sampler</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      A Mobility Sampler
      <ul>
        <li>Lunge Steps</li>
        <li>Crawl Position Side Reach</li>
        <li>Hip Up Crunches</li>
        <li>Side Jumps to Low Squat</li>
        <li>Gorilla Squats</li>
        <li>Kick Out Touches</li>
        <li>Belly Rows</li>
        <li>Squat Jumps</li>
      </ul>
    </td>
  </tr>
  <!-- Work Your Way Up To... -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1190506268612013">Work Your Way Up To...</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Work Your Way Up To:
      <ul>
        <li>Hanging Bar Toe-To-Bar</li>
        <li>Handstand Push Up</li>
      </ul>
    </td>
  </tr>
  <!-- Work Your Way Up To Handstands -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/468654559090750">Work Your Way Up To Handstands</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Work Your Way Up To Handstands
    </td>
  </tr>
  <!-- Work up to Handstand Pushup -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/428233173502580">Work up to Handstand Pushup</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Work up to Handstand Pushup
    </td>
  </tr>
  <!-- Do This After Long Sitting Periods -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/452528181003650">Do This After Long Sitting Periods</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Do This After Long Sitting Periods
      <ul>
        <li>Side Kick Downdog Twist</li>
        <li>Knee Cross Kicks to One Arm Opener</li>
        <li>Ninja Turn</li>
        <li>Pike Touch to Seated Combo</li>
      </ul>
    </td>
  </tr>
  <!-- Single Exercise for Lower Back -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1221533979332110">Single Exercise for Lower Back</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Single Exercise for Lower Back
      <ul>
        <li>Seated Toe Touches</li>
      </ul>
    </td>
  </tr>
  <!-- Pushup Variations -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/403287992141638">Pushup Variations</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Pushup Variations
    </td>
  </tr>
  <!-- Better Pushhps -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1116272942782877">Better Pushhps</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Better Pushhps (Workup to Planch)
    </td>
  </tr>
  <!-- Crunch Variations -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1619842755538238">Crunch Variations</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Crunch Variations
    </td>
  </tr>

  <!-- Crunches With Chair  -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1841930969691649">Crunches with a Chair</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Awesome core workout that uses a chair
      <ul>
        <li>Split then Center</li>
        <li>Feet together: Left then Right</li>
        <li>One foot top, one foot bottom then switch feet</li>
        <li>Feet together: Switch top to botton</li>
      </ul>
    </td>
  </tr>

</table>

<!--
*
* Cardio-Mobility
*
-->

<h2>Cardio-Mobility</h2>
Exercises that improve your mobility and also get your heart going.

<table border="1" width="100%">
  <!-- twist squats -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1629284027719823">Twist Squats</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      <ul>
        <li>Straight Leg Kicks</li>
        <li>Twist Jump Squats</li>
        <li>Running in Place</li>
        <li>Jump Squats</li>
        <li>Kicks With Arm Twists</li>
      </ul>
    </td>
  </tr>
  <!-- lunges with arms -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/948374670494802">Lunges with Arms</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      <ul>
        <li>Knee Taps</li>
        <li>Jump Squats</li>
        <li>Running in Place</li>
        <li>Lunges with Arms</li>
        <li></li>
      </ul>
    </td>
  </tr>
  <!-- kneeling -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/652373577579755">Kneeling</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      <ul>
        <li>Kneeling Pelvis Thrusts</li>
        <li>Kneeling Side Leans</li>
        <li>Kneeling Arm Raises</li>
        <li>Kneeling Head Hold Side Leans</li>
        <li></li>
      </ul>
    </td>
  </tr>
  <!-- -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1261959532161211">Bench</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      <ul>
        <li>Bench Double Side Taps</li>
        <li>Bench Two Foot Kicks</li>
        <li>Bench One Foot Kicks</li>
        <li>Bench Two Foot Kick Outs</li>
      </ul>
    </td>
  </tr>
  <!-- Cardio Core Workout  -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/718790187221659">Simple Cardio/Core</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Simple Cardio/Core workout (run etc. in place). Keep up if you can. Good luck.  
    </td>
  </tr>
  <!-- Cardio Core Floor Routine  -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/701156936252848">Floor Routine for Core</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Simple floor routine for core (min space requirement).  
    </td>
  </tr>
  <!-- Cardio Core Stair Routine  -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1305002831208236">Stair Routine for Core</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Simple routine for core you can do on stairs (stairs required).  
    </td>
  </tr>

  <!-- -->
  <!--
  <tr>
    <td valign="top" width="20%">
      <a href=""></a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      <ul>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </td>
  </tr>
  -->

</table>

<!--
*
* Dancing
*
-->

<h2>Dancing</h2>
Links to Dancing Tutorials

<table border="1" width="100%">
  <!-- Beginner Shuffle Dancing -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.youtube.com/watch?v=Kt-Tb9gaOB8">Beginner Shuffle Dancing</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Beginner Shuffle Dancing: All you really need to know (except for moon walking).
      Everything else is just variations ;)
    </td>
  </tr>
  <!-- Beginner Moonwalk -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.youtube.com/watch?v=eYT48mu-TIc&t=28s">Beginner Moonwalk</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Beginner Moonwalk
    </td>
  </tr>
  <!-- Moon Walk Variations -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1417431365879933">Moon Walk Variations</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Moon Walk Variations
    </td>
  </tr>
  <!-- Mobility Exercises to Work Up to Breakdancing -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/446174835053680">Mobility Exercises to Work Up to Breakdancing</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Mobility Exercises to Work Up to Breakdancing
    </td>
  </tr>
  <!-- How to Learn Break Dancing Swipes -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1078471720304481">How to Learn Break Dancing Swipes</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      How to Learn Break Dancing Swipes
      <ul>
        <li>Learn the Circle Motion</li>
        <li>Circle Motion with a Jumping Switch</li>
        <li>Circle Motion with Jumping Hands and Legs</li>
        <li>Explode into One Leg</li>
        <li>One Leg Half Turn on Knees</li>
        <li>One Leg Half Turn on Feet</li>
        <li>Full Turn on Feet</li>
        <li>Full Turn with Hand Switch</li>
        <li>Full Turn with Hand Switch One Leg</li>
        <li>Two Consecutive Turns</li>
        <li>Start from Standing and Add Turns</li>
        <li>Keep Practicing!!!</li>
      </ul>
    </td>
  </tr>

  <!-- -->
  <!--
  <tr>
    <td valign="top" width="20%">
      <a href=""></a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">

    </td>
  </tr>
  -->

</table>  

<!--
*
* Skiing
*
-->

<h2>Skiing</h2>
Links to Skiing Conditioning and Tutorials.

<table border="1" width="100%">

  <!-- one foot jumps -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/909141710790553">One Foot Jumps</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      One foot side to side jump exercise for conditioning for skiing moguls.
    </td>
  </tr>
  <!-- hard core ski workout -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.youtube.com/shorts/3Q1wPfN3gDQ">Hard Core Ski Workout</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Lots of intense exercises to get you ready for skiing moguls etc.
    </td>
  </tr>

  <!-- Impact Training for Skiing -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/1066404138643764">Impact Training for Skiing</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Impact Training for Skiing
    </td>
  </tr>
  
  <!-- -->
  <!--
  <tr>
    <td valign="top" width="20%">
      <a href=""></a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">

    </td>
  </tr>
  -->
</table>  
  
<!--
*
* Guitar Stuff
*
-->

<h2>Guitar Stuff</h2>
Ok, this one is more mental fitness than physicAL fitness.  

<table border="1" width="100%">

  <!-- 7ths chords trick  -->
  <tr>
    <td valign="top" width="20%">
      <a href="https://www.facebook.com/reel/2779138715603727">Cool 7ths Trick for 1/4/5 Progression</a>&nbsp;&nbsp;&nbsp;
    </td>
    <td valign="top">
      Use the tritone created by the 7th and the 3rd to find 1/4/5 chords that are all adjacent (i.e. move the tritone 1 fret)
    </td>
  </tr>

</table>
  

